name: test
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      - name: sqlite3
        run: sqlite3 ./testdata/sqlite/data/data.db < ./testdata/sqlite/create.sql
      - name: Build
        run: go build .
      - name: Test
        run: go test -v ./...
